name: Run applier

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    environment: payload_input
    env:
      REPOSITORY_LINK: ${{ github.server_url }}/${{ github.repository }}
      ACTION_RUN_LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      CV_LINK: ${{ vars.CV_LINK }}
      EMAIL: ${{ vars.EMAIL }}
      FULL_NAME: ${{ vars.FULL_NAME }}
      SIGNING_SECRET: ${{ vars.SIGNING_SECRET }}    
      
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - run: python applier.py
